In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Vimukthi Lakshan\Desktop\My Projects\sales data\global_ecommerce_sales.csv")

In [3]:
df

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,02/01/2023,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,02/01/2023,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,03/01/2023,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,03/01/2023,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,05/01/2023,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD-10823,31/12/2025,Linda Nilsson,Consumer,France,Europe,Furniture,Folding Table Portable,5,104.73,0,523.65,19.10,190.36,PayPal
1996,ORD-10896,31/12/2025,Ayumi Dubois,Consumer,France,Europe,Clothing & Accessories,Cotton Formal Shirt,11,59.27,5,619.37,20.94,272.44,PayPal
1997,ORD-11148,31/12/2025,Barbara Jones,Consumer,Spain,Europe,Technology,Webcam HD 1080p,6,31.79,15,162.13,15.19,42.03,Bank Transfer
1998,ORD-11519,31/12/2025,Maria Suzuki,Home Office,Spain,Europe,Clothing & Accessories,Sports Water Bottle 750ml,5,9.50,5,45.12,14.25,7.12,Credit Card
1999,ORD-11701,31/12/2025,Susan Russo,Home Office,South Korea,Asia Pacific,Clothing & Accessories,Sports Water Bottle 750ml,11,28.27,0,310.97,36.23,119.26,Credit Card

In [4]:
# 1. Create the Product Catalog (Dimension Table)
# We drop duplicates so each product exists only once
product_catalog = df[['Product_Name', 'Product_Category']].drop_duplicates().reset_index(drop=True)

In [6]:
product_catalog

                      Product_Name        Product_Category
0    Wireless Bluetooth Headphones              Technology
1       Mechanical Gaming Keyboard              Technology
2       Binder Clips Assorted 48pc         Office Supplies
3                  Webcam HD 1080p              Technology
4          Standing Desk Converter               Furniture
5                 Bookshelf 5-Tier               Furniture
6          Premium Notebook Set A5         Office Supplies
7          Laptop Stand Adjustable              Technology
8           Folding Table Portable               Furniture
9        Leather Wallet Minimalist  Clothing & Accessories
10           Paper Clips Box 500pc         Office Supplies
11             Travel Backpack 30L  Clothing & Accessories
12       Tape Dispenser Heavy Duty         Office Supplies
13          Business Casual Blazer  Clothing & Accessories
14            Corner L-Shaped Desk               Furniture
15          Ergonomic Office Chair               Furniture
16                Wool Blend Scarf  Clothing & Accessories
17        Whiteboard Markers Set 8         Office Supplies
18             Smart LED Desk Lamp              Technology
19  Sticky Notes Multicolor 6-Pack         Office Supplies
20              Desk Calendar 2025         Office Supplies
21       Floating Wall Shelves Set               Furniture
22       Portable External SSD 1TB              Technology
23               Stapler Full-Size         Office Supplies
24            Canvas Messenger Bag  Clothing & Accessories
25           Ballpoint Pen Pack 12         Office Supplies
26             Silk Tie Collection  Clothing & Accessories
27             Cotton Formal Shirt  Clothing & Accessories
28     USB-C Hub Multiport Adapter              Technology
29             Tablet Stand Holder              Technology
30       Sports Water Bottle 750ml  Clothing & Accessories
31        Noise Cancelling Earbuds              Technology
32              Monitor Riser Wood               Furniture
33            Leather Belt Classic  Clothing & Accessories
34              Desk Organizer Set               Furniture
35        Wireless Ergonomic Mouse              Technology
36            Mesh Back Task Chair               Furniture
37            Polarized Sunglasses  Clothing & Accessories
38        Highlighters Neon Pack 6         Office Supplies
39         Filing Cabinet 3-Drawer               Furniture

In [7]:

# We remove the descriptive columns that are now in the catalog, 
# keeping 'Product_Name' as the link (Foreign Key).
sales_data = df.drop(columns=['Product_Category', 'Unit_Price'])

In [8]:
sales_data

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Name,Quantity,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,02/01/2023,Karen Suzuki,Corporate,United States,North America,Wireless Bluetooth Headphones,3,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,02/01/2023,John Johansson,Corporate,Spain,Europe,Mechanical Gaming Keyboard,4,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,03/01/2023,Jessica Garcia,Consumer,Mexico,North America,Binder Clips Assorted 48pc,2,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,03/01/2023,Clara Taylor,Corporate,Italy,Europe,Webcam HD 1080p,2,15,105.16,10.79,26.32,PayPal
4,ORD-11454,05/01/2023,Felix Thomas,Consumer,Italy,Europe,Standing Desk Converter,4,20,1058.14,11.09,253.44,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD-10823,31/12/2025,Linda Nilsson,Consumer,France,Europe,Folding Table Portable,5,0,523.65,19.10,190.36,PayPal
1996,ORD-10896,31/12/2025,Ayumi Dubois,Consumer,France,Europe,Cotton Formal Shirt,11,5,619.37,20.94,272.44,PayPal
1997,ORD-11148,31/12/2025,Barbara Jones,Consumer,Spain,Europe,Webcam HD 1080p,6,15,162.13,15.19,42.03,Bank Transfer
1998,ORD-11519,31/12/2025,Maria Suzuki,Home Office,Spain,Europe,Sports Water Bottle 750ml,5,5,45.12,14.25,7.12,Credit Card
1999,ORD-11701,31/12/2025,Susan Russo,Home Office,South Korea,Asia Pacific,Sports Water Bottle 750ml,11,0,310.97,36.23,119.26,Credit Card

In [9]:
# Save to new CSV files
product_catalog.to_csv('product_catalog.csv', index=False)
sales_data.to_csv('sales_data.csv', index=False)

print("Tables successfully split!")

Tables successfully split!